### ISSUE TITLE
client.connect fails to connect to API server

### ISSUE THREAD

**Issue by Proj2501** [jfessard/espbtc#1]
Is this example still working with api.coinbase.com?  I tried to port this over to an M5Stack core (it utilizes the ESP32), but the client.connect(server, 443) line always responds with a failed connection for me.

**Comment by jfessard** [comment]
Unfortunately I haven't used it in a long time, you might want to find
recent examples/docs for coinbase's latest API. It's possible they don't
allow unauthenticated queries anymore? (I haven't checked)

**Comment by jfessard** [comment]
I just tried a query from my computer, and the API still works. 
```
$curl api.coinbase.com//v2/prices/BTC-USD/buy
{"data":{"base":"BTC","currency":"USD","amount":"51060.13"}}
```
so the issue is probably somewhere else on your stack. Did you try pinging the API endpoint or any other https site directly?

**Comment by Proj2501** [comment]
Thank you for responses--especially considering that you haven't used this code in a while.
The API documentation indicates that the price requests used here still work with unauthenticated requests, and the server responds just fine when the request is submitted via web browser.  The ESP32 code is having trouble just connecting to the api site before the GET request is even sent.  I'll keep searching to see if there are more recent examples of success or reports of the same trouble.  Thanks again for the discussion.
